### ISSUE TITLE
Tag Node releases for Homebrew

### ISSUE THREAD

**Issue by tcoenraad** [OiNutter/node-build#100]
For `homebrew` [tags](https://github.com/Homebrew/homebrew/blob/master/CONTRIBUTING.md) are used to identify a build. Because of that, I'd like to ask you to tag every Node release, so node-build's [formula](https://github.com/Homebrew/homebrew) can be updated. The latest tag only gives access to [Node 5.1.0](https://github.com/OiNutter/node-build/tree/v2.0.3/share/node-build), but I'd like to use later versions.

**Comment by jasonkarns** [comment]
I'll see about getting another node-build release out soon. (Currently, I'd like to wait until the jxcore 0.3.1.0 and -dev builds are fixed)

Until then, I recommend the [node-build-update-defs](https://github.com/jasonkarns/node-build-update-defs) plugin. This is the plugin that node-build itself uses to scrape nodejs and create new build definitions. If you install the plugin yourself, you can pull down node releases before node-build ships the definitions.

This is also documented in the node-build readme, but the plugin repo itself has more details: https://github.com/OiNutter/node-build#update-available-build-versions

**Comment by tcoenraad** [comment]
You could tag like [ruby-build](https://github.com/rbenv/ruby-build/releases) does, so tag every new release and use a timestamp as tag. In that way `nodenv` is more similar to `rbenv` and `pyenv`.

**Comment by jasonkarns** [comment]
We use npm's version script to bump our version so we use semver versions
instead of timestamps

**Comment by jasonkarns** [comment]
2.1.0 [tagged](https://github.com/OiNutter/node-build/releases/tag/v2.1.0)

https://github.com/Homebrew/homebrew/pull/47567
