### ISSUE TITLE
Download official binaries

### ISSUE THREAD

**Issue by maxnordlund** [OiNutter/node-build#11]
I saw that the README was changed for [nodenv][1] and it [reminded me][2] to [open an issue][3] to first download the official binaries and compile as a fallback, instead of always compiling. I browsed through wfarr's version and found [where it does the download][4]. Hopefully this helps, as I don't know enough to incorporate this myself.

[1]: /OiNutter/nodenv
[2]: /OiNutter/nodenv/issues/5
[3]: /Homebrew/homebrew/issues/28955
[4]: /wfarr/nodenv/blob/master/libexec/nodenv-install#L56-L81

**Comment by jasonkarns** [comment]
@peterkc would you be able to submit a PR to incorporate precompiled binaries into the built-in definitions somehow? (does ruby-build already do something like this? how does it handle the target platform)

This precompiled binary feature is currently blocking getting @OiNutter's nodenv/node-build into homebrew has the default nodenv formula.

**Comment by peterkc** [comment]
Jason,

I will do it today.


- Peter C

**Comment by jasonkarns** [comment]
here's an existing discussion on ruby-build for doing binaries: https://github.com/sstephenson/ruby-build/issues/42

**Comment by blackjid** [comment]
any news on this??

**Comment by jasonkarns** [comment]
BINARIES!!! 474e872d9acd5cc61c909f58d1521626d8c9d385

**Comment by maxnordlund** [comment]
Awesome :heart: :fireworks:
