### ISSUE TITLE
Merge upstream ruby-build changes

### ISSUE THREAD

**Issue by charlesbjohnson** [OiNutter/node-build#27]
Howdy,

I have several branches lined up for the recent iojs releases (1.0.0 through 1.1.0) that I want to eventually get merged in. However, they fail to build because the [current implementation of checksum verification](https://github.com/OiNutter/node-build/blob/df67cec08280250a64fb29e7b4380af6a4d95038/bin/node-build#L162-L186) assumes sha1 which is incompatible with the [sha256 backed checksums](https://iojs.org/dist/v1.0.0/SHASUMS256.txt) being used for iojs releases. As such, I would need to do some tweaking beyond the typical one-liners I've been adding to `share/node-build` in order to get the iojs releases to properly build.

Before I embark on any changes that would cause us to further divert from ruby-build, however, I thought it might be worthwhile to pull in the compatible upstream changes/features that have been made in ruby-build. Considering the difference in build versions (`201300310` vs `20150130`), I think a few things have changed :stuck_out_tongue:.

What are your thoughts? I'm more than happy to see this process through and make a PR for it, but I just wanted to make sure that you would be receptive to these changes before I spend the time making them. It might also be worth discussing how to handle future upstream changes.

Thanks!

**Comment by charlesbjohnson** [comment]
Hey @OiNutter I'm sure you are busy but even a quick :+1: or :-1: would be perfect.

**Comment by OiNutter** [comment]
Hi

Yeah, sorry, just not been able to get to even look at some of this stuff. Definitely on board with getting nodenv up to date with the latest rbenv/ruby-build changes but not sure when I'm going to have chance to look at that. If you've got time and are willing to do it and submit a pull request then go for it. I'll try and be a bit sharper and checking it out and responding this time.

**Comment by jasonkarns** [comment]
I just merged #53 which brings us up to Oct 2013.

And I just opened #54 which brings us to 2014. But #54 needs some work before it can be merged. @charlesbjohnson do you think you could help get the tests correct in #54 so we can continue?

**Comment by jasonkarns** [comment]
Keeping this open as a tracker, but I'm steadily merging in updates from ruby-build upstream. As of now, we're up to June 2014 [v20140524](https://github.com/sstephenson/ruby-build/tree/v20140524)

**Comment by jasonkarns** [comment]
current with latest ruby build tag ([v20151024](https://github.com/sstephenson/ruby-build/tree/v20151024)) as of Oct 24
