### ISSUE TITLE
Skip installing nodejs version if already present

### ISSUE THREAD

**Issue by chetandhembre** [OiNutter/node-build#55]
Hi, 
I am not finding skip option in installing node version if it is already present. 
Does node-build support it ? It will be awesome if it support it.
Thanks!!

**Comment by jawshooah** [comment]
What is your use case? Are you just installing everything listed in `nodenv install --list`?

If that's the case, why not just filter out the ones already listed in `nodenv versions`? Here's a script to do just that:

```bash
#!/bin/sh
{ nodenv versions | sed 's/[\* ]/ /g' | awk '{print $1}' ;
  nodenv install --list | tail -n +2 | awk '{print $1}' ;
} | sort -u
```

**Comment by jasonkarns** [comment]
I'm not sure if this existed before, or if it recently came to node-build through a merge from upstream ruby-build. But either way, node-build will prompt for confirmation before overwriting an existing installation:

```
$ nodenv versions 
* system (set by /usr/local/var/nodenv/version)
  0.10
  0.10.36
$ nodenv install 0.10.36 
nodenv: /usr/local/var/nodenv/versions/0.10.36 already exists
continue with installation? (y/N) 
```

**Comment by SampsonCrowley** [comment]
This is not a good API for automation. there should be an option same as rbenv for situations when _automatically_ installing a pre-specified version to just continue if the specified version is already a version installed on the system
