### ISSUE TITLE
Node Scraper doesn't find Node v4.0.0 release

### ISSUE THREAD

**Issue by kavington** [OiNutter/node-build#62]
Hello, thanks for the tool.

Running the scraper fails to find v4.0.0. 

Suspect it's to do with the distribution not having a SHASUMS.txt, instead declaring SHASUMS256.txt, (see http://nodejs.org/dist/v4.0.0/) which could be affecting line 6 of https://github.com/OiNutter/node-build/blob/master/tools/node_scraper.js .

Thanks!

**Comment by jasonkarns** [comment]
closed by #63

**Comment by kavington** [comment]
:metal:
