### ISSUE TITLE
add subcommand to run the scraper as a user

### ISSUE THREAD

**Issue by jasonkarns** [OiNutter/node-build#79]
The scraper is really helpful for adding node definitions to node-build directly. But it would be more awesome if the scraper could be invoked by a user through a subcommand so that users could get latest definitions even before they are in master.

Concerns:
- scraper requires node, so the command may fail if run on certain (older) versions of node
- scraper would fail if the command is run on a system without any nodes installed
- any new definitions would appear as new (untracked) files in node-build/share; this could prevent simple `git pull` from succeeding when those same definitions become available in master (breaking nodenv-update); this might impact homebrew installs as well. Solution? Write user-generated definitions to the custom-definition directory.

**Comment by jasonkarns** [comment]
I hacked up a new plugin the other night that accomplishes this.

I extracted the scraper from node-build into the plugin. node-build already reads any definitions from all plugins' share/node-build directory, so the plugin simply writes new definitions to its own share/node-build directory (optionally overridden with a command line flag). It looks up existing definitions in all known NODE_BUILD_DEFINITIONS paths and only writes defs for versions not already found in those paths. (--force flag allows it to write existing definitions).

Having the scraper be its own plugin avoids the problem of scraped definitions preventing a `git pull` of node-build. Also, with it being its own plugin, one can drop in a `.node-version` file into the plugin's directory to control the version of node that the scraper runs on.

The biggest question at this point is what to name it. Keeping in mind the plugin creates new build definitions for new nodes by scraping iojs.org and nodejs.org:

- update-defs
- update-version-defs
- pull-defs
- write-defs
- latest-defs
- scrape-defs
- scrape-versions
- latest-versions
- new-builds

@ianks @charlesbjohnson @jawshooah

**Comment by jawshooah** [comment]
I think `update-version-defs` may be best. Makes it very clear exactly what you're doing.

**Comment by jasonkarns** [comment]
thanks for the feedback @jawshooah 

I just pushed node-build-update-defs plugin with nodenv subcommand `nodenv update-version-defs`.

And opened #87 which would remove the scraper and script from node-build, instead leveraging the plugin itself to generate new definitions for node-build.
