### ISSUE TITLE
Update Homebrew version

### ISSUE THREAD

**Issue by herrstucki** [OiNutter/node-build#91]
The version on Homebrew is outdated. I can still install the most recent with `brew [re]install --HEAD node-build` but I think node-build should be properly re-published to the Homebrew directory when new build definitions are available.

**Comment by jasonkarns** [comment]
latest release as v2.0.2

brew PR https://github.com/Homebrew/homebrew/pull/46576

thanks!

**Comment by herrstucki** [comment]
Thanks! :smile:
