### ISSUE TITLE
scrape jxcore builds as well

### ISSUE THREAD

**Issue by jasonkarns** [OiNutter/node-build#95]
See https://github.com/jxcore/jxcore/issues/686 for the planned dist.json file structure.

**Comment by ktrzeciaknubisa** [comment]
Will node-build be able to compile unreleased jxcore branch on git? Say currently we work on 0.3.1.0, while the latest released is 0.3.0.7. Now if someone wants to build a chosen branch (0.3.1.0 or even master) - will he/she be able do it?

**Comment by jasonkarns** [comment]
Yes, node-build has the capability to compile from source, from git. However, node-build will not ship with a build definition for it, as we only include build definitions for actual releases, not edge/devel/master.

An example definition file that pulls from git can be found here: https://github.com/jxcore/jxcore/issues/675#issuecomment-162602200

As node-build accepts plugins via nodenv, other build definitions can be distributed via plugin. node-build looks for any definition files under `share/node-build/` in all nodenv plugin directories. Additionally, this path of definition directories can be customized via colon-separated: `NODE_BUILD_DEFINITIONS`.

It would be trivial to create a node-build plugin that included a build definition for jxcore-edge. (It could also include build definitions for nodejs-edge as well)

What's the desire here? For personal use, or would this potentially be jxcore's recommended way for building from master? If the latter, perhaps the nodenv team would consider relaxing the release-only restriction and include an -edge definition in node-build proper.

**Comment by ktrzeciaknubisa** [comment]
Thanks for the explanation

> What's the desire here? For personal use, or would this potentially be jxcore's recommended way for building from master?

I asked this bearing in mind those users, for which manual building is not so straight-forward. Many times we had a situation, when after an issue have been fixed, users were asking "when it will be released" or "thanks, I'll wait for the release". If node-build was offering an easy/just-few-lines-command way of compiling it, I think people would find it useful. But if that would need some extra configuration steps, making the thing more sophisticated for regular users, then maybe usability of it looses its value.

**Comment by jasonkarns** [comment]
I suppose it depends. *if* we ship with a `jxcore-edge` build definition, then for nodenv users with node-build installed the recommended way (which is the default if they `brew install nodenv`) , the following would build the latest from jxcore master, and make it available to nodenv as `jxcore-edge`:

```
nodenv install jxcore-edge
```

If they aren't already nodenv users, then they would either need to install nodenv, or [install node-build standalone](https://github.com/OiNutter/node-build#using-node-build-standalone). (`brew install node-build`). then they can run node-build manually

```
node-build jxcore-edge <path_to_output_jxcore>
```

(And, FWIW, homebrew isn't the only way to install nodenv/node-build. They can each be installed manually via git-clone)

**Comment by jasonkarns** [comment]
@ktrzeciaknubisa is the master branch where most dev occurs on jxcore? I see there is a 0.3.1.1 branch created now for the next release. If we had a jxcore-dev build, would it be okay to pull from master? (For our sake, I hope so because that would mean the -dev build wouldn't need to be updated each time there's a new release.)

**Comment by jasonkarns** [comment]
@ktrzeciaknubisa PR to add jxcore+v8-dev and jxcore+sm-dev builds, each pulling from jxcore/master https://github.com/OiNutter/node-build/pull/98

**Comment by jasonkarns** [comment]
PR to scrape jxcore versions: https://github.com/jasonkarns/node-build-update-defs/pull/4

This is blocked until jxcore publishes an official release manifest.json (pr was spiked against https://github.com/ktrzeciaknubisa/jxcore-issues/blob/master/index.json)

**Comment by ktrzeciaknubisa** [comment]
Thanks @jasonkarns 

> is the master branch where most dev occurs on jxcore?

So far we were following this kind of workflow: once we make a release (e.g. 0.3.1.0) - we're done with it. Then we create a new tag (e.g. 3.1.1.1) and all dev is going to the new branch. However every few commits/days we also merge it to the master. I think for now we can assume the same pattern will be continued.

**Comment by jasonkarns** [comment]
> Then we create a new tag (e.g. 3.1.1.1)

(assuming you meant branch here, since a tag would be stationary).

Under the flow you described, I think we'll still be better off to build off master. It means users won't be able to build from the *very* latest commits (since those would be in the release branches). But if that work is merged into master regularly, then the delay should be minimal. I think the tradeoff is worth the ability to leave the -dev definitions untouched, without the need to update the branch name each time a new release drops.

**Comment by jasonkarns** [comment]
closing this in favor of  jasonkarns/node-build-update-defs#4
